# Use root/docker as user/password credentials

services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer:4
    ports:
      - 8091:8080
    environment:
      ADMINER_DESIGN: pepa-linha
